name: My Safari
favicon: null
layout_spectrum: 0.24169
typography_spectrum: 0.60997
title: 'Training videos- https://vimeo.com/146592388'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f3e918'
    - '#82cbaf'
    - '#383838'
    - '#877e79'
    - '#ff4e5c'
  brandStrength: 0.1875
  lightness: 0.375
  saturation: 0.3125
  rhythmicContrast: 0.25
purpose: []
