name: My Safari
favicon: null
layout_spectrum: 0.17948032706044614
typography_spectrum: 0.9802504060789943
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.7741928526666015
  lightness: 0.8284777873195708
  saturation: 0.6344076073728502
  rhythmicContrast: 0.4493686417117715
purpose: []
