name: My Safari
favicon: null
layout_spectrum: 0.17948032706044614
typography_spectrum: 0.9802504060789943
title: Training videos
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f3e918'
    - '#82cbaf'
    - '#383838'
    - '#877e79'
    - '#ff4e5c'
  brandStrength: 0.5
  lightness: 0.375
  saturation: 0.6344076073728502
  rhythmicContrast: 0.4493686417117715
purpose: []
